version: '3.9'

services:

  web:
    build: .
    command: sh -c "until nc -z db 5432; do sleep 1; done && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env