# Generated by Django 4.2.6 on 2023-10-27 16:24
from django.contrib.auth.models import User, Group
from django.db import migrations


def forward_func(apps, schema_editor):
    User.objects.create_superuser(username='admin', email=None, password='admin')
    Group.objects.get_or_create(name='FILMS')
    Group.objects.get_or_create(name='PEOPLE')
    Group.objects.get_or_create(name='LOCATIONS')
    Group.objects.get_or_create(name='SPECIES')
    Group.objects.get_or_create(name='VEHICLES')


def reverse_func(apps, schema_editor):
    User.objects.all().delete()
    Group.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func)
    ]
